In [168]:
import pandas as pd

orders = pd.read_csv("olist_orders_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
order_reviews = pd.read_csv("olist_order_reviews_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
customers = pd.read_csv("olist_customers_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")
geo = pd.read_csv("olist_geolocation_dataset.csv")
payments = pd.read_csv("olist_order_payments_dataset.csv")


orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"],
    format="%Y-%m-%d %H:%M:%S",
    errors="coerce"
)

orders["order_delivered_customer_date"] = pd.to_datetime(
    orders["order_delivered_customer_date"],
    format="%Y-%m-%d %H:%M:%S",
    errors="coerce"
)

orders["order_estimated_delivery_date"] = pd.to_datetime(
    orders["order_estimated_delivery_date"],
    format="%Y-%m-%d %H:%M:%S",
    errors="coerce"
)

# Nivel 2

In [169]:
#6
df_1 = orders.merge(order_items, on = "order_id", how = "left")
df_1 = df_1.merge(products, on = "product_id", how = "left")
df_1.pivot_table(
    values = "price", 
    index = "product_category_name",
    columns = "order_status",
    aggfunc = "sum"
)

order_status,approved,canceled,delivered,invoiced,processing,shipped,unavailable
product_category_name,,,,,,,
agro_industria_e_comercio,NaN,NaN,70566.10,19.50,NaN,1944.87,NaN
alimentos,NaN,149.90,28731.15,NaN,221.60,290.76,NaN
alimentos_bebidas,NaN,60.00,14942.88,62.80,8.00,105.80,NaN
artes,NaN,35.00,23657.30,NaN,224.90,285.44,NaN
artes_e_artesanato,NaN,NaN,1814.01,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
sinalizacao_e_seguranca,NaN,NaN,21315.05,NaN,139.90,54.28,NaN
tablets_impressao_imagem,NaN,NaN,7528.41,NaN,NaN,NaN,NaN
telefonia,NaN,1324.89,309860.23,4654.13,4475.14,3353.14,NaN
telefonia_fixa,NaN,1758.79,55315.21,NaN,2492.50,16.50,NaN
utilidades_domesticas,169.9,5422.86,615628.69,1005.68,1858.23,8163.30,NaN

In [170]:
#7
df_1.pivot_table(
    values = "price", 
    index = "product_category_name",
    columns = "order_status",
    aggfunc = "mean"
)

order_status,approved,canceled,delivered,invoiced,processing,shipped,unavailable
product_category_name,,,,,,,
agro_industria_e_comercio,NaN,NaN,342.553883,19.500000,NaN,388.974000,NaN
alimentos,NaN,149.900000,57.577455,NaN,44.320000,58.152000,NaN
alimentos_bebidas,NaN,30.000000,55.549740,15.700000,8.000000,52.900000,NaN
artes,NaN,35.000000,120.087817,NaN,32.128571,71.360000,NaN
artes_e_artesanato,NaN,NaN,75.583750,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
sinalizacao_e_seguranca,NaN,NaN,108.198223,NaN,139.900000,54.280000,NaN
tablets_impressao_imagem,NaN,NaN,90.703735,NaN,NaN,NaN,NaN
telefonia,NaN,73.605000,69.945876,221.625238,248.618889,57.812759,NaN
telefonia_fixa,NaN,586.263333,216.922392,NaN,498.500000,16.500000,NaN
utilidades_domesticas,169.9,110.670612,90.600249,71.834286,68.823333,104.657692,NaN

In [171]:
#8
df_1.pivot_table(
    values = "freight_value",
    index = "product_category_name",
    columns = "order_status",
    aggfunc = "mean"
)

order_status,approved,canceled,delivered,invoiced,processing,shipped,unavailable
product_category_name,,,,,,,
agro_industria_e_comercio,NaN,NaN,27.365049,8.720000,NaN,39.536000,NaN
alimentos,NaN,17.760000,14.155371,NaN,15.614000,22.334000,NaN
alimentos_bebidas,NaN,9.685000,16.337881,11.850000,14.520000,15.905000,NaN
artes,NaN,16.600000,19.432640,NaN,19.108571,16.645000,NaN
artes_e_artesanato,NaN,NaN,15.422083,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
sinalizacao_e_seguranca,NaN,NaN,32.880914,NaN,18.550000,11.730000,NaN
tablets_impressao_imagem,NaN,NaN,14.773494,NaN,NaN,NaN,NaN
telefonia,NaN,14.022778,15.652910,12.056190,21.676667,16.855690,NaN
telefonia_fixa,NaN,15.990000,17.652275,NaN,14.880000,14.110000,NaN
utilidades_domesticas,9.56,19.178980,21.010090,18.502857,13.631852,23.193846,NaN

In [172]:
#9
df_1.pivot_table(
    values = "freight_value",
    index = "product_category_name",
    columns = "order_status",
    aggfunc = "mean",
    fill_value = 0
)

order_status,approved,canceled,delivered,invoiced,processing,shipped,unavailable
product_category_name,,,,,,,
agro_industria_e_comercio,0.00,0.000000,27.365049,8.720000,0.000000,39.536000,0.0
alimentos,0.00,17.760000,14.155371,0.000000,15.614000,22.334000,0.0
alimentos_bebidas,0.00,9.685000,16.337881,11.850000,14.520000,15.905000,0.0
artes,0.00,16.600000,19.432640,0.000000,19.108571,16.645000,0.0
artes_e_artesanato,0.00,0.000000,15.422083,0.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...
sinalizacao_e_seguranca,0.00,0.000000,32.880914,0.000000,18.550000,11.730000,0.0
tablets_impressao_imagem,0.00,0.000000,14.773494,0.000000,0.000000,0.000000,0.0
telefonia,0.00,14.022778,15.652910,12.056190,21.676667,16.855690,0.0
telefonia_fixa,0.00,15.990000,17.652275,0.000000,14.880000,14.110000,0.0
utilidades_domesticas,9.56,19.178980,21.010090,18.502857,13.631852,23.193846,0.0

In [173]:
#10
df_1.pivot_table(
    values = "price",
    index = ["product_category_name", "seller_id"],
    columns = "order_status",
    aggfunc = "mean"
)

order_status                                                approved  \
product_category_name     seller_id
agro_industria_e_comercio 06579cb253ecd5a3a12a9e6eb6bf8f47       NaN
                          0ed6ce5d87fd9c69eaacaeb778d67235       NaN
                          1996942dc085d7773ba77a529b163cd0       NaN
                          2528744c5ef5d955adc318720a94d2e7       NaN
                          269cff2d3c8d205c11f37a52402ea93b       NaN
...                                                              ...
utilidades_domesticas     f8f35af4634605e6693c17cc3ffff5a8       NaN
                          fa18c782a4866d313cadab567097f8f1       NaN
                          fa7ad8ae9bcb2c4493fdf38e96b1d74f       NaN
                          fc4751cfe3b279c419615b9b00c1abb4       NaN
                          fe87f472055fbcf1d7e691c00b1560dc       NaN

order_status                                                canceled  \
product_category_name     seller_id
agro_industria_e_comercio 06579cb253ecd5a3a12a9e6eb6bf8f47       NaN
                          0ed6ce5d87fd9c69eaacaeb778d67235       NaN
                          1996942dc085d7773ba77a529b163cd0       NaN
                          2528744c5ef5d955adc318720a94d2e7       NaN
                          269cff2d3c8d205c11f37a52402ea93b       NaN
...                                                              ...
utilidades_domesticas     f8f35af4634605e6693c17cc3ffff5a8       NaN
                          fa18c782a4866d313cadab567097f8f1     58.99
                          fa7ad8ae9bcb2c4493fdf38e96b1d74f       NaN
                          fc4751cfe3b279c419615b9b00c1abb4       NaN
                          fe87f472055fbcf1d7e691c00b1560dc       NaN

order_status                                                  delivered  \
product_category_name     seller_id
agro_industria_e_comercio 06579cb253ecd5a3a12a9e6eb6bf8f47    93.400000
                          0ed6ce5d87fd9c69eaacaeb778d67235   136.150000
                          1996942dc085d7773ba77a529b163cd0          NaN
                          2528744c5ef5d955adc318720a94d2e7  1249.000000
                          269cff2d3c8d205c11f37a52402ea93b   180.422500
...                                                                 ...
utilidades_domesticas     f8f35af4634605e6693c17cc3ffff5a8    90.000000
                          fa18c782a4866d313cadab567097f8f1          NaN
                          fa7ad8ae9bcb2c4493fdf38e96b1d74f          NaN
                          fc4751cfe3b279c419615b9b00c1abb4   453.700000
                          fe87f472055fbcf1d7e691c00b1560dc   180.966667

order_status                                                invoiced  \
product_category_name     seller_id
agro_industria_e_comercio 06579cb253ecd5a3a12a9e6eb6bf8f47       NaN
                          0ed6ce5d87fd9c69eaacaeb778d67235       NaN
                          1996942dc085d7773ba77a529b163cd0       NaN
                          2528744c5ef5d955adc318720a94d2e7       NaN
                          269cff2d3c8d205c11f37a52402ea93b       NaN
...                                                              ...
utilidades_domesticas     f8f35af4634605e6693c17cc3ffff5a8       NaN
                          fa18c782a4866d313cadab567097f8f1       NaN
                          fa7ad8ae9bcb2c4493fdf38e96b1d74f       NaN
                          fc4751cfe3b279c419615b9b00c1abb4       NaN
                          fe87f472055fbcf1d7e691c00b1560dc       NaN

order_status                                                processing  \
product_category_name     seller_id
agro_industria_e_comercio 06579cb253ecd5a3a12a9e6eb6bf8f47         NaN
                          0ed6ce5d87fd9c69eaacaeb778d67235         NaN
                          1996942dc085d7773ba77a529b163cd0         NaN
                          2528744c5ef5d955adc318720a94d2e7         NaN
                          269cff2d3c8d205c11f37a52402ea93b         NaN
...                                                                ...
utilidades_domesticas     f8f35af4634605e6693c17cc3ffff5a8         NaN
                          fa18c782a4866d313cadab567097f8f1         NaN
                          fa7ad8ae9bcb2c4493fdf38e96b1d74f        44.0
                          fc4751cfe3b279c419615b9b00c1abb4         NaN
                          fe87f472055fbcf1d7e691c00b1560dc         NaN

order_status                                                shipped  \
product_category_name     seller_id
agro_industria_e_comercio 06579cb253ecd5a3a12a9e6eb6bf8f47      NaN
                          0ed6ce5d87fd9c69eaacaeb778d67235      NaN
                          1996942dc085d7773ba77a529b163cd0   559.99
                          2528744c5ef5d955adc318720a94d2e7      NaN
                          269cff2d3c8d205c11f37a52402ea93b      NaN
...                                                             ...
utilidades_domesticas     f8f35af4634605e6693c17cc3ffff5a8      NaN
                          fa18c782a4866d313cadab567097f8f1      NaN
                          fa7ad8ae9bcb2c4493fdf38e96b1d74f      NaN
                          fc4751cfe3b279c419615b9b00c1abb4      NaN
                          fe87f472055fbcf1d7e691c00b1560dc      NaN

order_status                                                unavailable
product_category_name     seller_id
agro_industria_e_comercio 06579cb253ecd5a3a12a9e6eb6bf8f47          NaN
                          0ed6ce5d87fd9c69eaacaeb778d67235          NaN
                          1996942dc085d7773ba77a529b163cd0          NaN
                          2528744c5ef5d955adc318720a94d2e7          NaN
                          269cff2d3c8d205c11f37a52402ea93b          NaN
...                                                                 ...
utilidades_domesticas     f8f35af4634605e6693c17cc3ffff5a8          NaN
                          fa18c782a4866d313cadab567097f8f1          NaN
                          fa7ad8ae9bcb2c4493fdf38e96b1d74f          NaN
                          fc4751cfe3b279c419615b9b00c1abb4          NaN
                          fe87f472055fbcf1d7e691c00b1560dc          NaN

[6359 rows x 7 columns]

# Nivel 3

In [174]:
# 11
df_11 = order_items
df_11["total"] = df_11.apply(
    lambda fila: fila["price"] + fila["freight_value"],
    axis = 1
)
df_11

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04
...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,343.40
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,386.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,116.85
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,64.71
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,55.79

In [175]:
#12
print(order_items["price"].mean())

df_12 = order_items
def costo(x):
    if x >= 100:
        return "caro"
    else:
        return "barato"
df_12["categoria_precio"] = df_12["price"].apply(costo)
df_12

120.65373901464713

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total,categoria_precio
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19,barato
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83,caro
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87,caro
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78,barato
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04,caro
...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,343.40,caro
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,386.53,caro
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,116.85,barato
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,64.71,barato
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,55.79,barato

Se utilizó ese umbral debido a que el promedio de los productos es 120.

In [176]:
#13
df_13 = order_items
df_13["precio_flete"] = df_13.apply(
    lambda fila:
    True if fila["freight_value"] > fila["price"] * 0.2
    else False,
    axis = 1
)
df_13

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total,categoria_precio,precio_flete
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19,barato,True
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83,caro,False
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87,caro,False
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78,barato,True
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04,caro,False
...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,343.40,caro,False
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,386.53,caro,False
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,116.85,barato,False
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,64.71,barato,False
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,55.79,barato,True

In [177]:
#14
df_14 = products
df_14 = df_14.dropna()
df_14["category_mayus"] = df_14["product_category_name"].apply(
    lambda x: x.upper()
)
df_14

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,category_mayus
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,PERFUMARIA
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,ARTES
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,ESPORTE_LAZER
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,BEBES
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,UTILIDADES_DOMESTICAS
...,...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0,MOVEIS_DECORACAO
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0,CONSTRUCAO_FERRAMENTAS_ILUMINACAO
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0,CAMA_MESA_BANHO
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0,INFORMATICA_ACESSORIOS
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0,CAMA_MESA_BANHO

In [178]:
#15
df_14["palabra_det"] = df_14["product_category_name"].apply(
    lambda x: "bebes" in x.lower()
)
df_14

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,category_mayus,palabra_det
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,PERFUMARIA,False
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,ARTES,False
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,ESPORTE_LAZER,False
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,BEBES,True
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,UTILIDADES_DOMESTICAS,False
...,...,...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0,MOVEIS_DECORACAO,False
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0,CONSTRUCAO_FERRAMENTAS_ILUMINACAO,False
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0,CAMA_MESA_BANHO,False
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0,INFORMATICA_ACESSORIOS,False
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0,CAMA_MESA_BANHO,False

# Nivel 4

In [179]:
#16
df_16 = order_items.merge(products, on = "product_id", how = "left")
def costo(x):
    if x >= 100:
        return "caro"
    else:
        return "barato"
df_16["categoria_precio"] = df_16["total"].apply(costo)
df_16.pivot_table(
    values = "total",
    index= "product_category_name",
    columns = "categoria_precio",
    aggfunc= "mean"
)

categoria_precio              barato        caro
product_category_name
agro_industria_e_comercio  50.373205  555.559403
alimentos                  56.447593  152.498415
alimentos_bebidas          49.001387  200.628500
artes                      66.378065  190.298707
artes_e_artesanato         39.644667  176.607778
...                              ...         ...
sinalizacao_e_seguranca    52.230545  250.243708
tablets_impressao_imagem   65.520000  134.612708
telefonia                  43.771565  286.573990
telefonia_fixa             46.540411  486.660254
utilidades_domesticas      56.369358  212.013392

[73 rows x 2 columns]

In [180]:
#17
df_17 = order_items
df_17["envio"] = df_17.apply(
    lambda fila: fila["freight_value"] *100 / fila["price"], axis = 1
)

def clasificar_envio(x):
    if x > 0.2:
        return "envío alto"
    else:
        return "envío bajo"

df_17["categoria_envio"] = df_17["envio"].apply(clasificar_envio)
df_17.pivot_table(
    values= ["freight_value", "price", "envio"],
    index= "categoria_envio",
    aggfunc = "mean"
)

                     envio  freight_value       price
categoria_envio
envío alto       32.215852      20.070969  120.718530
envío bajo        0.013087       0.015408  104.606711

In [181]:
#18
df_18 = order_items.merge(products, on ="product_id", how = "left")
promedio = df_18["price"].mean()

def clasificar_precio(x):
    if x > promedio:
        return "Precio superior"
    else:
        return "Precio inferior"

df_18["clasificacion"] = df_18["price"].apply(clasificar_precio)
df_18.pivot_table(
    values = "price",
    columns = "clasificacion",
    index = "product_category_name",
    aggfunc = "mean"
)

clasificacion              Precio inferior  Precio superior
product_category_name
agro_industria_e_comercio        40.734432       556.014839
alimentos                        47.661030       163.258409
alimentos_bebidas                38.841882       229.339130
artes                            75.669405       425.158333
artes_e_artesanato               32.198125       162.355000
...                                    ...              ...
sinalizacao_e_seguranca          52.856483       256.389630
tablets_impressao_imagem         78.512025       331.490000
telefonia                        32.304922       304.369015
telefonia_fixa                   40.585455       534.206061
utilidades_domesticas            50.952542       230.277143

[73 rows x 2 columns]

In [182]:
#19
df_19 = order_items.merge(products, on  = "product_id", how = "left")
df_19.pivot_table(
    values = "price",
    index = "product_category_name",
    aggfunc= ["sum", "mean", "count"]
)

                                 sum        mean count
                               price       price price
product_category_name
agro_industria_e_comercio   72530.47  342.124858   212
alimentos                   29393.41   57.634137   510
alimentos_bebidas           15179.48   54.602446   278
artes                       24202.64  115.802105   209
artes_e_artesanato           1814.01   75.583750    24
...                              ...         ...   ...
sinalizacao_e_seguranca     21509.23  108.086583   199
tablets_impressao_imagem     7528.41   90.703735    83
telefonia                  323667.53   71.213978  4545
telefonia_fixa              59583.00  225.693182   264
utilidades_domesticas      632248.66   90.788148  6964

[73 rows x 3 columns]

# Nivel 5

Ejercicio 20. Pregunta: ¿Cómo afecta a la puntuación del pedido el hecho de que el costo del envío sea mayor o menor al promedio?

In [183]:
#20
df_20 = order_items.merge(order_reviews, on ="order_id", how = "left")
promedio = df_20["freight_value"].mean()

df_20["categoria_envio"] = df_20["freight_value"].apply(
    lambda x: "Envío mayor al promedio" if x > promedio else "Envío menor al promedio")

df_20.pivot_table(
    values = "review_score",
    index = "categoria_envio",
    aggfunc = ["mean", "count"]
)

                                mean        count
                        review_score review_score
categoria_envio
Envío mayor al promedio     3.943829        31208
Envío menor al promedio     4.066557        81164

Podemos observar que cuando el costo del envío es menor al promedio, la puntuación en las reseñas es un poco más alta (4.06) en comparación a aquillos con un envío superio al promedio (3.94).

Además, existen más pedidos realizados con un envío menor o igual al promedio.

In [184]:
#21
df_21 = order_items.merge(products, on = "product_id", how = "left")
df_21["porcentaje_flete"] = df_21.apply(
    lambda x: (x["freight_value"] / x["price"]) * 100, axis = 1)

df_21.pivot_table(
    values = ["price", "freight_value", "porcentaje_flete"],
    index = "product_category_name",
    aggfunc= "mean"
).sort_values(by = "porcentaje_flete", ascending= False)

                                freight_value  porcentaje_flete        price
product_category_name
casa_conforto_2                     13.677000         93.386243    25.342333
dvds_blu_ray                        20.136563         83.304467    93.740469
eletronicos                         16.833509         68.351661    57.913531
artigos_de_natal                    21.106536         67.565952    57.521699
fashion_underwear_e_moda_praia      14.627405         56.550343    72.836260
...                                       ...               ...          ...
relogios_presentes                  16.781160         17.058094   201.135984
portateis_casa_forno_e_cafe         36.156053         16.434979   624.285658
seguros_e_servicos                  20.610000         14.754843   141.645000
pc_gamer                            14.841111          9.655630   171.772222
pcs                                 48.454680          5.661292  1098.340542

[73 rows x 3 columns]

Las categorías que tienen mayor porcentaje de envío respecto al precio son productos que corresponden a artículos del hogar o multimedia, mientras que los que tienen menor porcentaje son los que tienen mayor precio, como artículos de tecnología o electrodomésticos.

## Ejercicio 22
Debido a que existían muchos nulos, simplifiqué a solo 3 categorías (entregado, no entregado y en proceso).

In [185]:
df_22 = orders.merge(order_items, on = "order_id", how = "left")
df_22 = df_22.merge(products, on = "product_id", how = "left")

def simplificado(x):
    if x == "delivered":
        return "entregado"
    elif x in ["canceled", "unavailable"]:
        return "no entregado"
    else:
        return "en proceso"

df_22["estatus_pedido"] = df_22["order_status"].apply(simplificado)

df_22['total'] = df_22.apply(
    lambda fila: fila["price"] + fila["freight_value"],
    axis=1
)

# Cantidad de pedidos por estatus y categoría
df_22.pivot_table(
    values = "order_id",
    columns = "estatus_pedido",
    index = "product_category_name",
    aggfunc = "count"
).sort_values(by="no entregado", ascending=False)

estatus_pedido               en proceso  entregado  no entregado
product_category_name
esporte_lazer                     159.0     8431.0          51.0
utilidades_domesticas             120.0     6795.0          49.0
informatica_acessorios            137.0     7644.0          46.0
beleza_saude                      169.0     9465.0          36.0
moveis_decoracao                  138.0     8160.0          36.0
...                                 ...        ...           ...
pcs                                 4.0      199.0           NaN
portateis_casa_forno_e_cafe         3.0       73.0           NaN
seguros_e_servicos                  NaN        2.0           NaN
sinalizacao_e_seguranca             2.0      197.0           NaN
tablets_impressao_imagem            NaN       83.0           NaN

[73 rows x 3 columns]

In [186]:
#22
# Costo total promedio por estatus y categoría
df_22.pivot_table(
    values = "total",
    columns = "estatus_pedido",
    index = "product_category_name",
    aggfunc = "mean"
).sort_values(by="no entregado", ascending=False)

estatus_pedido                      en proceso    entregado  no entregado
product_category_name
eletrodomesticos_2                  711.750000   511.725195    954.133333
cool_stuff                          203.366393   186.035742    896.688824
dvds_blu_ray                         34.530000    94.587541    741.880000
telefonia_fixa                      432.918333   234.574667    602.253333
construcao_ferramentas_iluminacao    64.040000   157.631694    576.310000
...                                        ...          ...           ...
pcs                                1112.417500  1147.486231           NaN
portateis_casa_forno_e_cafe         315.890000   674.601370           NaN
seguros_e_servicos                         NaN   162.255000           NaN
sinalizacao_e_seguranca             112.230000   141.079137           NaN
tablets_impressao_imagem                   NaN   105.477229           NaN

[73 rows x 3 columns]

In [187]:
# Reto final
df_23 = orders.merge(order_items, on = "order_id", how = "left")
df_23 = df_23.merge(products, on = "product_id", how = "left")

def simplificado(x):
    if x == "delivered":
        return "entregado"
    elif x in ["canceled", "unavailable"]:
        return "no entregado"
    else:
        return "en proceso"

df_23["estatus_pedido"] = df_23["order_status"].apply(simplificado)

df_23['total'] = df_23.apply(
    lambda fila: fila["price"] + fila["freight_value"],
    axis=1
)

df_23["porcentaje_flete"] = df_23.apply(
    lambda x: (x["freight_value"] / x["price"]) * 100, axis = 1)

df_23.pivot_table(
    values = ["price", "freight_value", "total", "porcentaje_flete"],
    index = ["product_category_name", "estatus_pedido"],
    aggfunc= "mean"
)

                                          freight_value  porcentaje_flete  \
product_category_name     estatus_pedido
agro_industria_e_comercio en proceso          34.400000         21.299069
                          entregado           27.365049         27.603192
alimentos                 en proceso          18.974000         48.724694
                          entregado           14.155371         34.576023
                          no entregado        17.760000         11.847899
...                                                 ...               ...
telefonia_fixa            entregado           17.652275         39.522033
                          no entregado        15.990000          5.440487
utilidades_domesticas     en proceso          20.381500         33.800723
                          entregado           21.010090         40.295417
                          no entregado        19.178980         51.984034

                                               price       total
product_category_name     estatus_pedido
agro_industria_e_comercio en proceso      327.395000  361.795000
                          entregado       342.553883  369.918932
alimentos                 en proceso       51.236000   70.210000
                          entregado        57.577455   71.732826
                          no entregado    149.900000  167.660000
...                                              ...         ...
telefonia_fixa            entregado       216.922392  234.574667
                          no entregado    586.263333  602.253333
utilidades_domesticas     en proceso       93.309250  113.690750
                          entregado        90.600249  111.610338
                          no entregado    110.670612  129.849592

[183 rows x 4 columns]